# Generated by Django 4.2 on 2023-09-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_custom_user_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
